# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confrmation_key',
            field=models.CharField(default='USER', max_length=40),
            preserve_default=False,
        ),
    ]
