# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170225_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='abc', max_length=254, unique=True, verbose_name='user name'),
            preserve_default=False,
        ),
    ]
