# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170227_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile_images/account.png', upload_to='profile_images/'),
        ),
    ]
