# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 20:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20170227_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_read_notif_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
