# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_last_read_notif_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
