# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_tenders_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenders',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
