# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationrequests',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_req', to='organizations.Organization'),
        ),
    ]
