# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clients_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='name',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='website',
        ),
        migrations.AddField(
            model_name='clients',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
