# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20170226_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
