# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientrequests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrequests',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='clientrequests',
            name='choices',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('', '')], default='', max_length=20),
        ),
    ]
