# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20170228_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientrequests',
            old_name='choices',
            new_name='status',
        ),
    ]
