# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_auto_20170219_1535'),
        ('users', '0005_auto_20170225_1704'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0004_quotes_amount'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotesAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('action', models.CharField(max_length=100)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Quotes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TendersAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('action', models.CharField(max_length=100)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.Tenders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
