# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20170225_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotesaudit',
            old_name='action',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='tendersaudit',
            old_name='action',
            new_name='message',
        ),
    ]
