# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('type', models.CharField(choices=[('tender', 'tender'), ('quote', 'quote')], max_length=100)),
                ('reference_id', models.CharField(choices=[('tender', 'tender'), ('quote', 'quote')], max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('status', models.PositiveIntegerField(choices=[(1, 'read'), (0, 'unread')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='quotenotifications',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='quotenotifications',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tendernotifications',
            name='tender',
        ),
        migrations.RemoveField(
            model_name='tendernotifications',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuoteNotifications',
        ),
        migrations.DeleteModel(
            name='TenderNotifications',
        ),
    ]
