# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20170226_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='reference_id',
            field=models.CharField(max_length=100),
        ),
    ]
