# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.Tenders')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
