# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20170219_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
